/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "uav_config.h"
#include "uav_app.h"
#include "uav_features.h"

/* Cortex-M4 FPU control register */
#define SCB_CPACR (*(volatile unsigned int *)0xE000ED88UL)

/*
 * These represent the two 500-sample accelerometer windows
 * that a real sensor would fill in deployment.
 */
static float x_window[UAV_WINDOW_SAMPLES];
static float y_window[UAV_WINDOW_SAMPLES];

static float features[UAV_FEATURE_COUNT];

volatile int g_uav_init_status = -1;
volatile int g_uav_prediction = -1;
volatile int g_uav_inference_done = 0;

static void enable_fpu(void)
{
    SCB_CPACR |= (0xFUL << 20);

    __asm volatile ("dsb 0xF" ::: "memory");
    __asm volatile ("isb 0xF" ::: "memory");
}

int main(void)
{
    enable_fpu();

    g_uav_init_status = uav_app_init();

    if (g_uav_init_status == 0)
    {
        /*
         * In real hardware:
         * x_window and y_window would be filled by the accelerometer.
         *
         * For resource measurement they are zero-filled placeholders.
         */
        g_uav_prediction =
            uav_predict_window(x_window, y_window, features);

        g_uav_inference_done = 1;
    }

    while (1)
    {
        __asm volatile ("nop");
    }
}
